version: '3.9'

services:
  app:
    container_name: galaga-app
    image: react-and-dot-app
    command: yarn start
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVER_PORT: {{env.SERVER_PORT}}
    restart: always
    ports:
      - '{{env.SERVER_PORT}}:{{env.SERVER_PORT}}'
    environment:
      - SERVER_PORT={{env.SERVER_PORT}}
    networks:
      - galaga
    depends_on:
      - galaga-db

  galaga-db:
    image: postgres:14
    ports:
      - '{{env.POSTGRES_PORT}}:{{env.POSTGRES_PORT}}'
    environment:
      POSTGRES_PASSWORD: {{env.POSTGRES_PASSWORD}}
      POSTGRES_USER: {{env.POSTGRES_USER}}
      POSTGRES_DB: {{env.POSTGRES_DB}}
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    networks:
      - galaga

  pgadmin:
    container_name: galaga-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '8080:80'
    depends_on:
      - galaga-db
    networks:
      - galaga

networks:
  galaga:
    driver: bridge
