#cloud-config
datasource:
 Ec2:
  strict_id: false
ssh_pwauth: no
users:
  - name: admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
     - {{ secrets.SERVER_SHH_KEY }}
