#cloud-config
datasource:
 Ec2:
  strict_id: false
ssh_pwauth: no
users:
- name: admin
  sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash
  ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGjWepFcT1TPCfIEWAN56ooAieaGaH/Vyh3A/UiEOL1l Aleksandr.Raykov@SP-RAYKOV1
