# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']

jobs:

stopdocker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Connect VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            sudo docker stop galaga-app
            sudo docker stop galaga-db
            sudo docker stop galaga-pgadmin
            sudo docker rm galaga-app
            sudo docker rm galaga-db
            sudo docker rm galaga-pgadmin

 rmdir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Connect VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            sudo rm -r app

  mkdir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Connect VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            mkdir app

  copy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "./*"
          target: "app"

  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Connect VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd app
            docker-compose up -d
